services:
  # 一个容器只绑定一个账号 + 一台云电脑，连接后永久保持串流
  ctyun-acc1:
    image: lusean23/ctyun-libclink-jni:latest
    container_name: ctyun-acc1
    restart: always
    ports:
      - "8572:8572"
    volumes:
      - ./data/acc1/app:/data
      - ./data/acc1/home:/root
    environment:
      TZ: Asia/Shanghai
      CTYUN_DATA_DIR: /data

  ctyun-acc2:
    image: lusean23/ctyun-libclink-jni:latest
    container_name: ctyun-acc2
    restart: always
    ports:
      - "8573:8572"
    volumes:
      - ./data/acc2/app:/data
      - ./data/acc2/home:/root
    environment:
      TZ: Asia/Shanghai
      CTYUN_DATA_DIR: /data
